"""Generate docs/tools.md from the tools the server registers.

    python scripts/gen_tools_doc.py            # rewrite docs/tools.md
    python scripts/gen_tools_doc.py --check    # exit 1 if docs/tools.md is out of date

tests/unit/test_docs.py runs the check, so the reference cannot drift from the code.
"""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path

from fastmcp import Client

from carmaker_mcp import server

OUT = Path(__file__).resolve().parent.parent / "docs" / "tools.md"

SECTIONS = [
    ("Setup", ("cm_session_start", "cm_doctor")),
    ("Run control", ("cm_status", "cm_load_testrun", "cm_start_sim", "cm_stop_sim", "cm_wait_end", "cm_log",
                     "cm_live", "cm_dva_write", "cm_dva_release", "cm_popups", "cm_popup_timeout",
                     "cm_gui_tcl")),
    ("Results", ("cm_results_list", "cm_results_summary", "cm_results_read", "cm_output_quantities",
                 "cm_output_quantities_edit")),
    ("IPGMovie", "movie"),
    ("Project data", ("cm_list", "cm_read", "cm_edit", "cm_clone")),
    ("MATLAB workspace and Simulink", "matlab"),
    ("Standalone instances (no MATLAB)", "standalone"),
    ("Parameter studies", "study"),
    ("History and undo", ("cm_changelog", "cm_revert_all", "cm_restore")),
]

HEADER = """\
# Tools

<!-- Generated by scripts/gen_tools_doc.py from the server's tool registry. Do not edit by hand. -->

All tools return JSON. Errors of the domain (bad path, simulation not idle, MATLAB unreachable, CarMaker
refusing something) come back as tool errors with a plain message; invalid arguments are rejected by the
input schema before anything runs.

Each tool is marked for MCP clients as **read-only**, **changes state** or **destructive** (overwrites
or discards something; all of these are logged and most can be undone with `cm_revert_all`).

Optional tools are registered only when their group is named in `CM_ENABLE`
({features}). Groups that can be switched off with `CM_DISABLE` to shorten the tool list:
{groups}.

Resources: `carmaker://guide` (how to use the server), `carmaker://status`, `carmaker://changelog`,
`carmaker://log`. Prompts: `run_and_summarise`, `compare_settings`, `undo_session`.
"""


def _kind(tool) -> str:
    a = tool.annotations.model_dump(by_alias=True) if tool.annotations else {}
    if a.get("readOnlyHint"):
        return "read-only"
    return "destructive" if a.get("destructiveHint") else "changes state"


def _type(schema: dict) -> str:
    if "enum" in schema:
        return " \\| ".join(f"`{v}`" for v in schema["enum"])
    if "anyOf" in schema:
        parts = [_type(s) for s in schema["anyOf"] if s.get("type") != "null"]
        return " \\| ".join(parts) + (" or null" if len(parts) < len(schema["anyOf"]) else "")
    t = schema.get("type", "any")
    if t == "array":
        return f"list of {_type(schema.get('items', {}))}"
    return {"number": "number", "integer": "integer", "string": "string", "boolean": "boolean",
            "object": "object"}.get(t, str(t))


def _default(name: str, schema: dict, required: list[str]) -> str:
    if name in required:
        return "required"
    d = schema.get("default")
    if d is None:
        return "null"
    if isinstance(d, bool):
        return f"`{str(d).lower()}`"
    return f'`"{d}"`' if isinstance(d, str) else f"`{d}`"


def _tool_md(tool, feature: str | None) -> list[str]:
    d = tool.model_dump(by_alias=True, exclude_none=True)
    schema = d["inputSchema"]
    props, required = schema.get("properties", {}), schema.get("required", [])
    note = f" · optional, needs `CM_ENABLE={feature}`" if feature else ""
    lines = [f"### `{tool.name}`", "", f"*{d.get('title', tool.name)}* · {_kind(tool)}{note}", "",
             " ".join((tool.description or "").split()), ""]
    if props:
        lines += ["| Parameter | Type | Default | Meaning |", "|---|---|---|---|"]
        for name, s in props.items():
            desc = " ".join(s.get("description", "").split()).replace("|", "\\|")
            lines.append(f"| `{name}` | {_type(s)} | {_default(name, s, required)} | {desc} |")
        lines.append("")
    return lines


def generate() -> str:
    async def listed():
        async with Client(server.create_server(set(server.FEATURES))) as c:
            return {t.name: t for t in await c.list_tools()}

    tools = asyncio.run(listed())
    features = {s.fn.__name__: s.feature for s in server._TOOLS}
    out = [HEADER.format(
        features=", ".join(f"`{k}`: {v}" for k, v in server.FEATURES.items()),
        groups=", ".join(f"`{k}` ({v})" for k, v in server.GROUPS.items()),
    )]
    seen: set[str] = set()
    for title, members in SECTIONS:
        if isinstance(members, str):
            names = [n for n in tools if server._group(n) == members]
        else:
            names = list(members)
        out += [f"## {title}", ""]
        for n in names:
            out += _tool_md(tools[n], features[n])
            seen.add(n)
    missing = set(tools) - seen
    if missing:
        raise SystemExit(f"tools without a section in gen_tools_doc.py: {sorted(missing)}")
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    text = generate()
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print("docs/tools.md is out of date: run `python scripts/gen_tools_doc.py`")
            return 1
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
